# Generated by Django 4.2.7 on 2023-11-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0006_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
    ]
