# Generated by Django 4.2.7 on 2023-11-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0008_alter_review_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='details',
            field=models.TextField(max_length=200),
        ),
    ]
