# Generated by Django 4.2.7 on 2023-11-17 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0011_rename_user_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='pfp',
            new_name='avatar',
        ),
    ]
