# Generated by Django 4.2.7 on 2023-11-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0014_remove_profile_avatar_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
